apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-java-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-java
  template:
    metadata:
      labels:
        app: ci-java
    spec:
      containers:
      - name: ci-java-container
        image: ci-java-app:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
