apiVersion: v1
kind: Service
metadata:
  name: devops-project-service
  namespace: prod
spec:
  type: NodePort
  selector:
    app: devops-project
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30009